version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "53:53"                # only required for Pro (DNS)
      - "53:53/udp"            # only required for Pro (DNS)
      - "443:443"              # only required for Pro (LocalStack HTTPS Edge Proxy)
      - "4510-4559:4510-4559"  # external service port range
      - "4566:4566"            # LocalStack Edge Proxy
    environment:
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - LAMBDA_REMOTE_DOCKER=false
      - BUCKET_MARKER_LOCAL=hot-code
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./lambda:/tmp/lambda"
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
